sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  # The default version of sqlite on travis doesn't support bulk inserts.
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1
install:
  - pip install -r dev-requirements.txt
  - pip install -e .
before_script:
  - docker-compose up -d
script:
  - ./scripts/copyright_line_check.sh
  - isort --check-only --verbose --recursive graphql_compiler/
  - flake8 --exclude **/snap_*.py graphql_compiler/
  - pydocstyle graphql_compiler/
  - pylint graphql_compiler/
  - bandit -r graphql_compiler/
  - py.test --cov=graphql_compiler graphql_compiler/tests
after_success:
  - docker-compose down
  - coveralls
